### ISSUE TITLE
alpha_isc

### ISSUE THREAD

**Issue by toddkarin** [hackingmaterials/pv-terms#12]
@cwhanse Technically, alpha_isc depends on temperature. Should we use alpha_isc_ref for alpha_isc at reference conditions and alpha_isc at any temperature?

**Comment by cwhanse** [comment]
That is my view, although I'd say "alpha_isc at any condition" there can be a spectral dependence as well.

**Comment by toddkarin** [comment]
We have decided to just use `alpha_isc` (i.e. no `_ref`) as it is typically assumed this value is at reference conditions.
