### ISSUE TITLE
DC output section missing terms

### ISSUE THREAD

**Issue by mdeceglie** [hackingmaterials/pv-terms#18]
I suggest adding `current_dc` `voltage_dc`, and `energy_dc` to the the DC Output section.

**Comment by toddkarin** [comment]
Sounds good, I've added them. The only question is whether energy is in Joules or kWh?

**Comment by cwhanse** [comment]
kWh, I've seen insolation in MJ but not in PV literature (in meteorology or agricultural contexts).

**Comment by mdeceglie** [comment]
I agree about not using something based on joules. RdTools uses Wh, and Wh would be more naturally consistent with pv-terms `power_dc ` being in watts, but kWh is much more common, so I could see it going either way.

Would the folks be open to adding a provision in pv-terms for units to be specified as a suffix when default units are not used? It further branches things, but at least it would be documented in a standard way. I think we have to find a compromise between flexibility, which will increase uptake of pv-terms and the ideal "one parameter" world.

**Comment by toddkarin** [comment]
Yes, I'd be happy to add units as another suffix. I will make a note in the documentation. Since neither Wh or kWh are SI units, lets just go for the more typically used kWh.

**Comment by toddkarin** [comment]
I just changed energy units to kWh, and added a further suffix in the user guide for different units.
