### ISSUE TITLE
Terms in incorrect sections

### ISSUE THREAD

**Issue by mdeceglie** [hackingmaterials/pv-terms#19]
I suggest that the sections for several terms should be shuffled a bit.

The following terms should be moved to the "Inverter" section:

- `efficiency_inverter`  
- `efficiency_inverter_eu`  
- `efficiency_inverter_cec`  

`spectral_mismatch` should be moved to the "Module Parameters" section

**Comment by toddkarin** [comment]
I moved the inverter efficiency as suggested.

spectral_mismatch isn't really a module parameter, it has to do with the difference between the module efficiency with AM1.5 and with the spectrum of interest. 

On the other hand, a parameter like photocurrent also isn't strictly a module parameter, having to do with both the properties of the module and the environment it is in. 

My main reason for putting spectral_mismatch in the PV system category is that is where it is in pvlib.

**Comment by mdeceglie** [comment]
I agree that those module terms are a gray area. Change looks good, thanks!
