### ISSUE TITLE
Normalized versions for gamma_pmp

### ISSUE THREAD

**Issue by mdeceglie** [hackingmaterials/pv-terms#21]
`gamma_pmp` and `gamma_pmp_ref` could use normalized version like `alpha_isc` and `beta_voc`.

**Comment by toddkarin** [comment]
I've added this.

**Comment by kandersolar** [comment]
I see these terms got added in this commit: https://github.com/DuraMAT/pv-terms/commit/5fed8ad9e34d03bb3a45304c5d4c88d9490da697

But I'm not seeing the terms in the CSV file on the current master.  Did they get lost somehow?

**Comment by toddkarin** [comment]
Yes, it seems to have been lost, I've added it back again.
