### ISSUE TITLE
Better organize PV System and PV Power Plant categories

### ISSUE THREAD

**Issue by cwhanse** [hackingmaterials/pv-terms#3]
Proposal:
- put inverter parameters in a new section
- PV System, containing variables related to current, voltage and power, could be "DC output" or "DC Power". transposition_factor doesn't belong here.  "spectral_mismatch" belongs with "effective_irradiance" perhaps.
- PV System should contain variables related to the physical PV system, including many quantities (modules_per_string, module_temperature) in PV Power Plant.
- I'm -1 (x 3) on the "_XX" pattern.  If the intent is to "demonstrate a naming scheme", OK, but let's keep the base names "voltage_dc" etc. in the glossary, and demonstrate a naming scheme using these base variables in an Examples section.

**Comment by toddkarin** [comment]
I'm happy with all those proposed changes. Note that the index.rst file is hardcoded, so we will need to update categories there too. Before making changes let's decide on the categories (new ones at the bottom). Any more we need?

- Abbreviations
- Optional Suffixes
- Location
- Atmosphere
- Solar Position
- Irradiance
- PV System
- PV Power Plant (remove?)
- Module Parameters
- DC Output (added)
- AC Output (added)

We will probably want another html page 'Modifying standard terms' where we can describe the _XX naming scheme and the suffixes. (e.g. choosing a standard order where multiple suffixes are appended.)

**Comment by kandersolar** [comment]
Inverter parameters?  Things like number of MPPT circuits, acceptable DC voltage/current ranges, max AC output.

**Comment by cwhanse** [comment]
Yes, and currently unnamed model parameters, see `pvlib.pvsystem.snlinverter`.

**Comment by toddkarin** [comment]
Okay, so our list will be:

- Abbreviations
- Optional Suffixes
- Location
- Atmosphere
- Solar Position
- Irradiance
- PV System
- PV Power Plant (remove?)
- Module Parameters
- DC Output
- AC Output
- Inverter Parameters

@cwhanse : Do you want to change these snlinverter parameters to conform with the naming convention?

**Comment by cwhanse** [comment]
Some of the SNL inverter model parameters don't have natural names, they are just polynomial coefficients. Others can be renamed, e.g., Pnt is power_night_tare or something like that.  Maybe naming model parameters can wait. We should add terms for the AC and DC capacities, max/nominal/min input voltage, etc. I'm OK having the structure and hoping someone more informed makes a PR to add the terms.

**Comment by toddkarin** [comment]
I'm making the changes you suggested now. 

I would say that we should for now avoid model parameters that aren't used widely. E.g. perhaps single diode model parameters are widely used but inverter model params for a particular model are of secondary interest for standardization.

**Comment by toddkarin** [comment]
There's also the question of how to deal with a parameter like pmp, which could be a module parameter or a PV system variable.

**Comment by toddkarin** [comment]
I made the changes you suggested and remade the html, check it out.

**Comment by cwhanse** [comment]
> I would say that we should for now avoid model parameters that aren't used widely. 

In this case, the Sandia/CEC inverter model is the most widely used. I'm OK putting off adding terms here until there's a request to do it.

**Comment by toddkarin** [comment]
Added new categories.
